"""Pydantic models for ephemeral specialist subagents.

Subagents are scoped, short-lived workers used by the shared Planner ->
Executor -> Reflector runtime. They receive bounded task packets and return
structured evidence for the top-level orchestrator to review.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class AgentRole(str, Enum):
    """Supported specialist roles in the orchestrator/subagent runtime."""

    HEALTH_ANALYSIS = "health_analysis"
    PLAYBOOK_RETRIEVAL = "playbook_retrieval"
    OUTREACH_DRAFT = "outreach_draft"
    CUSTOMER_CHAT = "customer_chat"
    COMPLIANCE_CRITIC = "compliance_critic"
    ACTION_EXECUTION = "action_execution"


class SubagentTask(BaseModel):
    """Bounded task packet created by an orchestrator planner."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    id: str = Field(description="Stable task ID generated by the orchestrator planner")
    role: AgentRole = Field(description="Specialist subagent role to instantiate")
    objective: str = Field(description="Single bounded outcome for this subagent")
    skill: str = Field(description="Role-specific instructions selected by the orchestrator")
    input: dict[str, Any] = Field(default_factory=dict)
    allowed_tools: list[str] = Field(default_factory=list)
    depends_on: list[str] = Field(default_factory=list)
    max_react_steps: int = Field(default=6, ge=1, le=12)
    max_tokens: int = Field(default=2000, ge=256, le=8000)
    output_format: Literal["markdown_and_json"] = "markdown_and_json"

    def is_ready(self, completed: set[str]) -> bool:
        """Return True when every declared dependency has completed."""
        return all(task_id in completed for task_id in self.depends_on)


class SubagentContextPacket(BaseModel):
    """Tenant-safe context passed to a single ephemeral subagent run."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    tenant_id: str
    customer_id: str # the customer being acted on (not the user)
    trace_id: str | None = None
    task: SubagentTask # the actual bounded task to execute
    tenant_constraints: list[str] = Field(default_factory=list)
    memory_excerpt: str | None = None
    # The processed textual text or raw dictionary payloads produced by previous subagents in the pipeline
    dependency_markdown: dict[str, str] = Field(default_factory=dict) # use by LM 
    dependency_data: dict[str, dict[str, Any]] = Field(default_factory=dict) # use by tool call / compliance critic


class ToolCallRecord(BaseModel):
    """Redacted audit record for a tool call made by a subagent."""

    model_config = ConfigDict(extra="forbid")

    tool_name: str
    success: bool
    arguments_redacted: dict[str, Any] = Field(default_factory=dict)
    result_redacted: dict[str, Any] = Field(default_factory=dict)


class SubagentResult(BaseModel):
    """Structured output returned by an ephemeral subagent."""

    model_config = ConfigDict(extra="forbid")

    task_id: str
    role: AgentRole
    success: bool
    markdown: str = Field(description="Human-readable summary for downstream review")
    data: dict[str, Any] = Field(default_factory=dict)
    tool_calls: list[ToolCallRecord] = Field(default_factory=list)
    tokens_used: int = 0
    error: str | None = None


__all__ = [
    "AgentRole",
    "SubagentTask",
    "SubagentContextPacket",
    "SubagentResult",
    "ToolCallRecord",
]
